apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: speedserver
    version : v1
  name: speedserver-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: speedserver
      version: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: speedserver
        version : v1
    spec:
      containers:
      - image: lalx/speedtest-server:v1
        name: speedserver
        resources: {}
status: {}

