apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: bootstrap-dr
spec:
  host: bootstrap-svc.eks-demo.svc.cluster.local
  subsets:
    - labels:
        version: v1
      name: v1
    - labels:
        version: v2
      name: v2

