kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: eks-user-group
  namespace: default
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: eks-user-group-binding
  namespace: default
subjects:
- kind: User
  name: eks_user
  namespace: mynamespace
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eks-user-group
