apiVersion: v1
kind: Service
metadata:
  labels:
    app: bootstrap
    version: v1
  name: bootstrap-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http-port
  selector:
    app: bootstrap
  type: ClusterIP
