apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: speedserver
    env: demo
    version : v2
  name: speedserver-v2
  namespace: eks-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: speedserver
      version: v2
  strategy: {}
  template:
    metadata:
      labels:
        app: speedserver
        version : v2
    spec:
      containers:
      - image: 957236318034.dkr.ecr.eu-north-1.amazonaws.com/speedtest-server:v2
        name: speedserver
        resources: {}
status: {}

