apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: speedserver
    env: demo
    version : v1
  name: speedserver-v1
  namespace: eks-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: speedserver
      version: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: speedserver
        version : v1
    spec:
      containers:
      - image: lalx/speedtest_server:v1.0
        name: speedserver
        resources: {}
status: {}

