apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: speedserver-dr
  namespace: eks-stage
spec:
  host: speedserver-svc.eks-stage.svc.cluster.local
  subsets:
    - labels:
        version: v2
      name: stage

