apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: speedserver-vs
  namespace: eks-stage
spec:
  hosts:
  - demo.alexakis.org
  gateways:
  - demo-gw
  http:
  - route:
    - destination:
        host: speedserver-svc.eks-stage.svc.cluster.local
        subset: base
      weight: 0
    - destination:
        host: speedserver-svc.eks-stage.svc.cluster.local
        subset: canary
      weight: 100
